version: "2.2"

services:

  memcached:
    image: memcached:alpine
    container_name: memcached
    environment:
      - "TZ=${TZ}"
    restart: always

  db:
    image: mysql:8.0.17
    container_name: sgaf_db
    command:
       - "--character-set-server=utf8mb4"
       - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

#  smtp_relay:
#    image: juanluisbaptiste/postfix
#    container_name: smtp_relay
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#    environment:
#      - "SERVER_HOSTNAME=helpdesk.singaren.net.sg"
#      - "SMTP_SERVER=${SMTP_SERVER}"
#      - "SMTP_USERNAME=${SMTP_USERNAME}"
#      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
#    restart: always

  jagger:
    image: spgreen/jagger:v1.8.0
    container_name: sgaf-resource-registry
    depends_on:
      - db
      - memcached
    ports:
      - 8081:80/tcp
    env_file:
      - ./.env
    restart: always

  pyffd:
     image: spgreen/pyffd:1.1.1
     container_name: sgaf-pyffd
     depends_on:
       - jagger
     mem_limit: 2g
     memswap_limit: 2g
     environment:
       - "PIPELINE=/metadata/sources/sgaf.fd"
       - "EXTRA_ARGS=--frequency=21600 -a"
       - "TZ=${TZ}"
     volumes:
       - ./metadata:/metadata
     ports:
       - 8080:8080/tcp
     restart: always

  wayf:
     image: spgreen/switch-wayf:2.0
     container_name: sgaf-wayf
     depends_on:
       - jagger
       - pyffd
     environment:
       - "METADATA_SOURCE=http://sgaf-pyffd:8080/sgaf-local.xml"
       - "TZ=${TZ}"
     volumes:
       - ./sgaf-wayf/config.php:/opt/wayf/etc/config.php
       - ./sgaf-wayf/singaren-logo.png:/opt/wayf/www/images/singaren-logo.png
       - ./sgaf-wayf/sgaf-ds-banner.png:/opt/wayf/www/images/sgaf-ds-banner.png
       - ./sgaf-wayf/custom-languages.php:/opt/wayf/lib/custom-languages.php
     ports:
       - 8083:80/tcp
     restart: always

